str1 = "ruchi singh!!!"
print(str1.upper())
print(str1.lower())
print(str1.strip())
print(str1.rstrip("!"))
print(str1.replace("ruchi", "shikha"))
print(str1.split(" "))
print(str1.capitalize())
print(str1.center(50, "."))
print(str1.count("i"))
print(str1.endswith("!!!"))
print(str1.find("hi"))
print(str1.find("shikha"))
print(str1.index("ch"))
print(str1.isalnum())
